#!/usr/bin/env node
/**
 * Fuutu Stack — brand asset pipeline.
 *
 * Source of truth: packages/config/assets/
 *   - logo.svg      (1:1 SVG, you provide this — adaptive dark mode via CSS inside the SVG)
 *   - og-image.png  (1200×630 PNG, you provide this — cannot be generated from the square logo)
 *
 * Generated from logo.svg:
 *   - favicon.svg               (copy of logo.svg, renamed for browser favicon convention)
 *   - favicon-96x96.png
 *   - apple-touch-icon.png      (180×180)
 *   - web-app-manifest-192x192.png
 *   - web-app-manifest-512x512.png
 *
 * Distributed to: apps/{saas,marketing,docs,mail-preview}/public/
 *
 * Usage:
 *   pnpm assets:sync                              # generate + sync everything
 *   pnpm assets:sync --skip favicon.svg           # leave favicon.svg untouched (generate + sync the rest)
 *   pnpm assets:sync --skip favicon.svg,apple-touch-icon.png
 *
 * --skip accepts a comma-separated list of filenames (as they appear in
 * packages/config/assets/). Skipped files are neither generated nor distributed.
 */

import { copyFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "../..");
const assets = join(root, "packages/config/assets");

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const SOURCE_SVG = "logo.svg";
const SOURCE_OG = "og-image.png";

// Files generated by rasterizing logo.svg → PNG at a given size.
// `file` is the output filename in packages/config/assets/.
const GENERATED_PNGS = [
	{ file: "favicon-96x96.png", size: 96 },
	{ file: "apple-touch-icon.png", size: 180 },
	{ file: "web-app-manifest-192x192.png", size: 192 },
	{ file: "web-app-manifest-512x512.png", size: 512 },
];

// favicon.svg is a copy of logo.svg (renamed for browser favicon convention).
const GENERATED_SVGS = ["favicon.svg"];

const APPS = ["saas", "marketing", "docs", "mail-preview"];

// Per-file destination: which subfolder of public/ does it land in?
// favicon/* PNGs + favicon.svg → public/favicon/
// logo.svg + og-image.png      → public/ (root)
function destDir(file) {
	if (file === "logo.svg" || file === "og-image.png") return "";
	return "favicon";
}

// ---------------------------------------------------------------------------
// CLI: --skip
// ---------------------------------------------------------------------------

const skipArg = process.argv.find((a) => a.startsWith("--skip="));
const skipSet = new Set(
	skipArg
		? skipArg
				.slice("--skip=".length)
				.split(",")
				.map((s) => s.trim())
				.filter(Boolean)
		: [],
);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function log(action, msg) {
	console.log(`  ${action.padEnd(6)} ${msg}`);
}

function isSkipped(file) {
	return skipSet.has(file);
}

function copyToApps(file) {
	if (isSkipped(file)) {
		log("SKIP", `${file} (--skip)`);
		return;
	}
	const src = join(assets, file);
	if (!existsSync(src)) {
		log("WARN", `${file} (source missing)`);
		return;
	}
	const sub = destDir(file);
	for (const app of APPS) {
		const dest = join(root, "apps", app, "public", sub, file);
		mkdirSync(dirname(dest), { recursive: true });
		copyFileSync(src, dest);
		const relPath = sub
			? `${app}/public/${sub}/${file}`
			: `${app}/public/${file}`;
		log("COPY", relPath);
	}
}

// ---------------------------------------------------------------------------
// Step 1 — generate derived assets from logo.svg
// ---------------------------------------------------------------------------

async function generate() {
	console.log("\n\u{1F3A8}  Generating derived assets from logo.svg\n");

	const logoSrc = join(assets, SOURCE_SVG);
	if (!existsSync(logoSrc)) {
		log("WARN", `${SOURCE_SVG} not found — skipping generation`);
		return;
	}

	// favicon.svg = copy of logo.svg
	for (const file of GENERATED_SVGS) {
		if (isSkipped(file)) {
			log("SKIP", `${file} (--skip)`);
			continue;
		}
		const dest = join(assets, file);
		copyFileSync(logoSrc, dest);
		log("GEN", `${file}  (= ${SOURCE_SVG})`);
	}

	// PNGs via sharp
	const sharp = (await import("sharp")).default;
	for (const { file, size } of GENERATED_PNGS) {
		if (isSkipped(file)) {
			log("SKIP", `${file} (--skip)`);
			continue;
		}
		const dest = join(assets, file);
		const svgBuf = readFileSync(logoSrc);
		await sharp(svgBuf, { density: 384 })
			.resize(size, size, {
				fit: "contain",
				background: { r: 0, g: 0, b: 0, alpha: 0 },
			})
			.png()
			.toFile(dest);
		log("GEN", `${file}  (${size}×${size})`);
	}
}

// ---------------------------------------------------------------------------
// Step 2 — distribute all assets to app public/ directories
// ---------------------------------------------------------------------------

function sync() {
	console.log("\n\u{1F4E4}  Syncing to apps\n");

	// Generated + source SVGs
	for (const file of [...GENERATED_SVGS, SOURCE_SVG]) {
		copyToApps(file);
	}

	// Generated PNGs
	for (const { file } of GENERATED_PNGS) {
		copyToApps(file);
	}

	// OG image (manual, not generated)
	copyToApps(SOURCE_OG);
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

const skipNote =
	skipSet.size > 0 ? `\n  Skipping: ${[...skipSet].join(", ")}\n` : "";

console.log(
	`\n\u2500\u2500 Fuutu Stack — asset pipeline \u2500\u2500${skipNote}`,
);

await generate();
sync();

console.log("\nDone.\n");
